GET http://localhost:9999/api/v1/task
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4ODQ4NzEsInVzZXJJZCI6MTAwfQ.S7fHEvIT0BcfosolHnLKTDvWalzz6pxlBmbYxGT8RXU

###
GET http://localhost:9999/api/v1/task/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4MzMxMzIsInVzZXJJZCI6MTAwfQ.oNRzulmzMm4ufUhWgF_-Uvd0Fz2tCO7DmhQ121yiyd8

###
POST http://localhost:9999/api/v1/task
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4NDYzMTgsInVzZXJJZCI6MTAwfQ.nTlTiw3y07pfnAe1OsGDy4zBY6zTQeOhpjCA7WQz3JI

{
  "taskId": "321",
  "description": "task description 444",
  "date": "2019-01-01T00:00:00Z",
  "isDone": true,
  "label": {
    "labelId": "3",
    "name": "Personal"
  }
}

###
PUT http://localhost:9999/api/v1/task/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI2MjY1MjgsInVzZXJJZCI6MTAwfQ.0UoQmIPAct3eBvpq0G3YU8yUR3oG0IfTbvzvKmRbf0U

{
  "description": "Tarea actualizada",
  "date": "2019-01-01T00:00:00Z"
}


###
DELETE http://localhost:9999/api/v1/task/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4Nzc0NTQsInVzZXJJZCI6MTAwfQ.8wc2Tlo9pX3Es9_kdChhT_En8lR0cPHxpT35SODGq7g

###
PUT http://localhost:9999/api/v1/task/2/done
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4Nzc0NTQsInVzZXJJZCI6MTAwfQ.8wc2Tlo9pX3Es9_kdChhT_En8lR0cPHxpT35SODGq7g